// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HttpGet(arg1, arg2, arg3) {
  return window['go']['network']['Network']['HttpGet'](arg1, arg2, arg3);
}

export function HttpPost(arg1, arg2, arg3) {
  return window['go']['network']['Network']['HttpPost'](arg1, arg2, arg3);
}
