// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HttpGet(arg1:string,arg2:Record<string, string>,arg3:Array<number>):Promise<Array<number>>;

export function HttpPost(arg1:string,arg2:Record<string, string>,arg3:Array<number>):Promise<Array<number>>;
