// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccountConfig() {
  return window['go']['account']['AccountBinding']['GetAccountConfig']();
}

export function SetAccountConfig(arg1) {
  return window['go']['account']['AccountBinding']['SetAccountConfig'](arg1);
}
