// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';

export function GetAccountConfig():Promise<account.AccountList>;

export function SetAccountConfig(arg1:account.AccountList):Promise<void>;
