// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfigTomlPath():Promise<string>;

export function LoadOrInitConfig():Promise<config.Config>;

export function ReadConfig():Promise<config.Config>;

export function WriteConfig(arg1:config.Config):Promise<void>;
