// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigTomlPath() {
  return window['go']['config']['ConfigBinding']['GetConfigTomlPath']();
}

export function LoadOrInitConfig() {
  return window['go']['config']['ConfigBinding']['LoadOrInitConfig']();
}

export function ReadConfig() {
  return window['go']['config']['ConfigBinding']['ReadConfig']();
}

export function WriteConfig(arg1) {
  return window['go']['config']['ConfigBinding']['WriteConfig'](arg1);
}
