// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigIniPath() {
  return window['go']['main']['App']['GetConfigIniPath']();
}

export function ReadConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadConfig'](arg1, arg2, arg3);
}

export function StartDownload() {
  return window['go']['main']['App']['StartDownload']();
}

export function WriteConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteConfig'](arg1, arg2, arg3, arg4);
}
